apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Values.name }}
    meta.helm.sh/release-namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: {{ .Values.image }}
          ports:
            - containerPort: 4533
          env:
            - name: ND_LOGLEVEL
              value: info
            - name: ND_SCANINTERVAL
              value: 10m
            - name: ND_SESSIONTIMEOUT
              value: 24h
            - name: ND_MUSICFOLDER
              value: /music
            - name: ND_DATAFOLDER
              value: /data
          volumeMounts:
            - name: music
              mountPath: /music
            - name: data
              mountPath: /data
      volumes:
        - name: music
          hostPath:
            path: {{ .Values.musicHostPath }}
            type: Directory
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Values.name }}-data-pvc
