apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Values.name }}-preinstall-patcher"
  namespace: "{{ .Values.namespace }}"
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      restartPolicy: Never
      serviceAccountName: default
      containers:
        - name: patcher
          image: registry.k8s.io/kubectl:v1.32.0
          command: ["/bin/sh", "-c"]
          args:
            - |
              set -ex
              for resource in "deployment/{{ .Values.name }}" "service/{{ .Values.name }}" "ingress/{{ .Values.name }}-ingress"; do
                kind="${resource%%/*}"
                name="${resource##*/}"
                kubectl patch "$kind" "$name" -n {{ .Values.namespace }} --type merge -p '{
                  "metadata": {
                    "labels": {
                      "app.kubernetes.io/managed-by": "Helm"
                    },
                    "annotations": {
                      "meta.helm.sh/release-name": "{{ .Values.name }}",
                      "meta.helm.sh/release-namespace": "{{ .Values.namespace }}"
                    }
                  }
                }' || true
              done
              kubectl patch pvc {{ .Values.name }}-data-pvc -n {{ .Values.namespace }} --type merge -p '{
                "metadata": {
                  "labels": {
                    "app.kubernetes.io/managed-by": "Helm"
                  },
                  "annotations": {
                    "meta.helm.sh/release-name": "{{ .Values.name }}",
                    "meta.helm.sh/release-namespace": "{{ .Values.namespace }}"
                  }
                }
              }' || true
