apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    "helm.sh/resource-policy": keep
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.name }}
  ports:
    - port: 80
      targetPort: 4533
